name: Atualizar estatísticas do perfil

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: atualizar-estatisticas-perfil
  cancel-in-progress: true

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v6

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Gerar card de estatísticas
        env:
          STATS_TOKEN: ${{ secrets.STATS_TOKEN }}
          ORG_STATS_TOKEN: ${{ secrets.ORG_STATS_TOKEN }}

        run: |
          python scripts/generate_github_card.py

      - name: Remover cards antigos
        run: |
          rm -f profile/stats.svg
          rm -f profile/top-langs.svg

      - name: Salvar estatísticas no repositório
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A profile/

          if git diff --cached --quiet; then
            echo "Nenhuma alteração nas estatísticas."
            exit 0
          fi

          git commit -m "Atualiza estatísticas do perfil"
          git push
